name: CI (Maven Multi-Module)

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.java'
      - '**/pom.xml'
      - 'backend/**'
      - 'frontend/**'
      - 'mobile/**'
      - 'common/**'
  pull_request:
    paths:
      - '**.java'
      - '**/pom.xml'
      - 'backend/**'
      - 'frontend/**'
      - 'mobile/**'
      - 'common/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test – ${{ matrix.module }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ backend, frontend, mobile, common ]

    env:
      BASE_URL: https://practice.expandtesting.com/
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21' # or 17 to need to match it to main pom.xml

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Cache Playwright browsers only for the frontend (web UI) module
      - name: Cache Playwright browsers (frontend only)
        if: matrix.module == 'frontend'
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: pw-${{ runner.os }}-

      - name: Build & Test (${{ matrix.module }})
        run: |
          mvn -B -fae -pl ${{ matrix.module }} -am test

      - name: Upload Surefire/Failsafe reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.module }}
          path: |
            ${{ matrix.module }}/target/surefire-reports/**
            ${{ matrix.module }}/target/failsafe-reports/**
          if-no-files-found: ignore

      - name: Upload Playwright traces & reports (frontend only)
        if: always() && matrix.module == 'frontend'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-${{ matrix.module }}
          path: |
            frontend/test-results/**
            frontend/playwright-report/**
          if-no-files-found: ignore

      - name: Upload mobile artifacts (mobile only)
        if: always() && matrix.module == 'mobile'
        uses: actions/upload-artifact@v4
        with:
          name: mobile-artifacts
          path: |
            mobile/target/**
            mobile/logs/**
          if-no-files-found: ignore
