# For DataBases CI
name: tests
on: [push, pull_request]
jobs:
  mvn:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: appdb
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U test -d appdb"
          --health-interval 5s --health-timeout 5s --health-retries 20
    env:
      DB_USER: test
      DB_PASS: test
      DB_HOST: localhost
      DB_NAME: appdb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21', cache: 'maven' }
      - name: Build & test
        run: mvn -B -Denv=ci clean verify
